// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A captured (possibly truncated, possibly decoded) message body.
 *
 * Bodies are never required to live fully in memory: `size` is the true
 * wire size, while `text`/`base64` hold at most a capped preview.
 */
export type BodyPreview = { 
/**
 * Full decoded size in bytes (may exceed the captured preview).
 */
size: bigint, 
/**
 * True when the preview was cut off at the memory cap.
 */
truncated: boolean, 
/**
 * The `Content-Type` media type, if known.
 */
media_type: string | null, 
/**
 * The `Content-Encoding` that was decoded away, if any.
 */
decoded_from: string | null, 
/**
 * UTF-8 preview when the (decoded) body is text.
 */
text: string | null, 
/**
 * Base64 preview when the (decoded) body is binary.
 */
base64: string | null, };
