// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of NovaProxy's root CA and its trust in the OS store.
 */
export type CaStatus = { 
/**
 * Absolute path of the persisted `ca.pem`.
 */
cert_path: string, 
/**
 * SHA-256 fingerprint (uppercase hex, colon-separated).
 */
fingerprint: string, 
/**
 * Whether the CA is currently trusted in the system store.
 */
trusted: boolean, 
/**
 * Human-readable subject line.
 */
subject: string, };
