// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What changed an exchange after it left the client.
 *
 * Three flags rather than one boolean, because "why is the response wrong?"
 * has three different answers and the table's Edited column is where that
 * question starts. Each is set only when something actually changed: a rule
 * that matched but had nothing to rewrite, or a script hook that returned the
 * headers it was given, leaves no mark — a marker that means "a rule exists"
 * rather than "this request was altered" would be noise on every row.
 */
export type Edits = { 
/**
 * A rule rewrote this: Block, Map Local, Map Remote, or a header Rewrite.
 */
rule: boolean, 
/**
 * The script hook changed headers, or aborted the request.
 */
script: boolean, 
/**
 * A person edited it while it was paused at a breakpoint.
 */
breakpoint: boolean, };
