// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BodyPreview } from "./BodyPreview";
import type { FlowState } from "./FlowState";
import type { Header } from "./Header";

/**
 * One request/response exchange captured by the proxy engine.
 */
export type Flow = { 
/**
 * Stable unique id assigned in `handle_request`.
 */
id: string, 
/**
 * Monotonic sequence number for stable ordering / display index.
 */
seq: bigint, method: string, scheme: string, host: string, path: string, url: string, 
/**
 * Remote client socket address (`ip:port`).
 */
client_addr: string, 
/**
 * PID of the local process that originated this request, if resolved.
 */
pid: number | null, 
/**
 * Name of the originating process (e.g. "Google Chrome"), if resolved.
 * Best-effort; `None` when attribution failed or on unsupported platforms.
 */
process: string | null, http_version: string, state: FlowState, status: number | null, request_headers: Array<Header>, response_headers: Array<Header>, request_body: BodyPreview | null, response_body: BodyPreview | null, 
/**
 * Bytes seen on the wire for the request body.
 */
request_size: bigint, 
/**
 * Bytes seen on the wire for the response body.
 */
response_size: bigint, 
/**
 * Response `Content-Type`, convenient for filtering.
 */
content_type: string | null, 
/**
 * Epoch milliseconds when the request was first seen.
 */
started_at: number, 
/**
 * Total wall-clock duration once completed.
 */
duration_ms: number | null, error: string | null, 
/**
 * True when this flow was produced by a Resend/Replay action.
 */
resent: boolean, 
/**
 * Original host if a Map Remote rule rewrote this request's destination.
 */
mapped_from: string | null, 
/**
 * True when this flow is a WebSocket upgrade; its frames stream on the
 * dedicated WS channel keyed by [`Flow::id`].
 */
is_websocket: boolean, 
/**
 * True when this CONNECT was tunneled without decryption (per the TLS
 * scope): only the host is known, no request/response bodies are captured.
 */
tunneled: boolean, };
