// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle of a flow as it streams through the proxy.
 */
export type FlowState = "Started" | "Paused" | "Completed" | "Error";
