// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single HTTP header, preserving order and duplicates (unlike a map).
 */
export type Header = { name: string, value: string, };
