// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single HTTP header, preserving order and duplicates (unlike a map).
 *
 * `PartialEq` so a caller can ask whether a header set actually changed —
 * which is what separates "a script ran" from "a script edited this".
 */
export type Header = { name: string, value: string, };
