// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * State of the macOS privileged helper, which applies system-proxy changes
 * without an administrator password.
 */
export type HelperStatus = { 
/**
 * Whether this platform needs a helper at all (macOS only; elsewhere the
 * proxy settings are per-user and need no privileges).
 */
supported: boolean, 
/**
 * A helper is installed and answering.
 */
running: boolean, 
/**
 * Protocol version it answered with, when running.
 */
version: number | null, 
/**
 * Protocol version this build speaks. A mismatch means "reinstall".
 */
expected_version: number, 
/**
 * A helper binary was found to install from. False in a build tree that
 * never built `nova-helper`.
 */
installable: boolean, };
