// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Header } from "./Header";

/**
 * A request held at a breakpoint, streamed to the UI so it can be edited and
 * then continued or aborted.
 */
export type Interception = { id: string, method: string, url: string, request_headers: Array<Header>, };
