// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpTransport } from "./McpTransport";

/**
 * What a captured flow carries when it is a Model Context Protocol exchange.
 * Present only on flows recognised as MCP (see `nova_core::mcp`).
 */
export type McpInfo = { 
/**
 * JSON-RPC method, e.g. `tools/call`.
 */
method: string | null, 
/**
 * For `tools/*` and `prompts/*`, the tool or prompt being invoked.
 */
tool: string | null, 
/**
 * JSON-RPC id, rendered as a string. Absent for notifications.
 */
id: string | null, transport: McpTransport, };
