// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * State of the MCP endpoint that exposes captured traffic to AI tooling.
 */
export type McpStatus = { running: boolean, 
/**
 * Port it is (or would be) served on.
 */
port: number, 
/**
 * Endpoint URL to hand an MCP client, when running.
 */
url: string | null, };
