// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Simulated network conditions applied to responses (throttling / latency).
 */
export type NetworkConditions = { enabled: boolean, 
/**
 * Extra delay added before each response starts, in milliseconds.
 */
latency_ms: number, 
/**
 * Downlink cap in kilobits/sec applied to response bodies (0 = unlimited).
 */
down_kbps: number, };
