// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current state of the proxy engine, returned by the `proxy_status` command.
 */
export type ProxyStatus = { running: boolean, host: string | null, port: number | null, flows_captured: bigint, 
/**
 * Whether the OS system proxy is currently pointed at NovaProxy.
 */
system_proxy: boolean, };
