// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current state of the proxy engine, returned by the `proxy_status` command.
 */
export type ProxyStatus = { running: boolean, host: string | null, port: number | null, flows_captured: bigint, 
/**
 * Whether the OS system proxy is currently pointed at NovaProxy.
 */
system_proxy: boolean, 
/**
 * A snapshot from a previous session is still waiting to be put back — the
 * app exited uncleanly while the system proxy was on, and restoring it
 * needs a privilege the app does not have unattended. The UI offers the
 * restore instead of the old behaviour, which raised a password dialog
 * during launch.
 */
pending_restore: boolean, };
