// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleKind } from "./RuleKind";

/**
 * A traffic-control rule. The action is selected by [`RuleKind`]; the relevant
 * optional fields are interpreted per kind (documented on each variant).
 */
export type Rule = { id: string, enabled: boolean, kind: RuleKind, name: string, 
/**
 * URL glob to match, `*` = wildcard, tested against `scheme://host/path`.
 */
pattern: string, 
/**
 * MapRemote: replacement base URL. MapLocal: absolute file path.
 */
target: string | null, 
/**
 * Rewrite: header name to set.
 */
header_name: string | null, 
/**
 * Rewrite: header value to set.
 */
header_value: string | null, };
