// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a matching [`Rule`] does.
 */
export type RuleKind = "MapRemote" | "MapLocal" | "Block" | "Rewrite";
