// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Measured timing breakdown of one exchange, in milliseconds.
 *
 * Every field is a real measurement or `None` — nothing here is estimated. A
 * phase is `None` when it genuinely did not happen or could not be observed:
 * DNS/connect/TLS are absent when the flow reused a pooled connection (see
 * `connection_reused`), and `tls` is absent on plaintext HTTP.
 */
export type Timings = { 
/**
 * Resolving the host name.
 */
dns_ms: number | null, 
/**
 * TCP handshake to the origin (or upstream proxy).
 */
connect_ms: number | null, 
/**
 * TLS handshake with the origin.
 */
tls_ms: number | null, 
/**
 * True when the request went out on an already-open connection, so no
 * DNS/connect/TLS cost is attributable to it.
 */
connection_reused: boolean, 
/**
 * Streaming the request body upstream (absent when there was no body).
 */
request_ms: number | null, 
/**
 * Request first seen → upstream response headers received.
 */
ttfb_ms: number | null, 
/**
 * Response headers → last response body byte.
 */
download_ms: number | null, };
