// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which hosts NovaProxy decrypts (MITM) versus tunnels through untouched.
 *
 * A host that pins its certificate or requires mTLS will abort NovaProxy's
 * leaf cert; tunneling it raw keeps the app working at the cost of visibility.
 */
export type TlsScope = { 
/**
 * When true, decrypt everything except hosts matching `exclude`. When
 * false, decrypt only hosts matching `include` (tunnel everything else).
 */
intercept_all: boolean, 
/**
 * Host globs to decrypt (used when `intercept_all` is false).
 */
include: Array<string>, 
/**
 * Host globs to tunnel without decrypting (used when `intercept_all`).
 */
exclude: Array<string>, };
