// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress of an update download, streamed while it runs.
 *
 * `total` is optional because it comes from a `Content-Length` the server is
 * not obliged to send; the UI shows a determinate bar only when it is present.
 */
export type UpdateProgress = { downloaded: bigint, total: bigint | null, 
/**
 * The bytes are in; installing (and then restarting) is next.
 */
done: boolean, };
