// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an update check found.
 *
 * `configured` is the honest answer to "can this build update itself at all":
 * the updater endpoint and public key are injected at release time, so a
 * development build has neither. Reporting it lets the UI say so instead of
 * offering a button that can only fail.
 */
export type UpdateStatus = { 
/**
 * Version this build reports, i.e. what an update would replace.
 */
current_version: string, 
/**
 * Whether this build has an updater endpoint and a signing key to verify
 * against.
 */
configured: boolean, 
/**
 * A newer version is published and passes signature verification.
 */
available: boolean, 
/**
 * Version on offer, when one is.
 */
version: string | null, 
/**
 * Release notes from the manifest.
 */
notes: string | null, 
/**
 * Publication date from the manifest, as the manifest spelled it.
 */
date: string | null, };
