// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Direction of a captured WebSocket frame, from the client's point of view.
 */
export type WsDirection = "Sent" | "Received";
