// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WsDirection } from "./WsDirection";
import type { WsOpcode } from "./WsOpcode";

/**
 * A single WebSocket frame captured on an upgraded [`Flow`]. Frames are
 * streamed to the UI on their own channel (keyed by [`WsMessage::flow_id`])
 * rather than folded into the flow snapshot, so a chatty socket doesn't
 * re-emit the whole flow per message.
 */
export type WsMessage = { 
/**
 * Id of the upgrade [`Flow`] this frame belongs to.
 */
flow_id: string, 
/**
 * Monotonic per-flow sequence for stable ordering.
 */
seq: bigint, direction: WsDirection, opcode: WsOpcode, 
/**
 * Full payload size in bytes (may exceed the retained preview).
 */
size: bigint, 
/**
 * True when the preview was cut off at the memory cap.
 */
truncated: boolean, 
/**
 * UTF-8 preview for text frames.
 */
text: string | null, 
/**
 * Base64 preview for binary/control payloads.
 */
base64: string | null, 
/**
 * Epoch milliseconds when the frame was seen.
 */
at: number, };
