// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of a captured WebSocket frame.
 */
export type WsOpcode = "Text" | "Binary" | "Ping" | "Pong" | "Close";
